# Generated by Django 4.0.3 on 2022-04-08 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создание')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновление')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаление')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создание')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновление')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаление')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категорий',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создание')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновление')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаление')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('brand', models.CharField(choices=[{'Gucci', 'gucci'}, {'Armani', 'armani'}, {'Nike', 'nike'}, {'prada', 'Prada'}, {'qazaq republic', 'Qazaq Republic'}, {'Adidas', 'adidas'}, {'fendi', 'Fendi'}, {'Dior', 'dior'}, {'Louis Vuitton', 'louis vuitton'}, {'Thrasher', 'thrasher'}], max_length=50, verbose_name='Брэнд')),
                ('img', models.ImageField(max_length=255, upload_to='clothes/')),
                ('country', models.CharField(max_length=50, verbose_name='Пройзводство')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('type_clothes', models.CharField(max_length=150, verbose_name='Ткань')),
                ('categories', models.CharField(choices=[{'рубашка', 'Рубашка'}, {'Юбка', 'юбка'}, {'брюки', 'Брюки'}, {'обувь', 'Обувь'}, {'кепка', 'Кепка'}, {'Носки', 'носки'}], default='рубашка', max_length=150, verbose_name='Категория')),
                ('price', models.IntegerField(verbose_name='Стоймость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежды',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создание')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновление')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаление')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=20, verbose_name='Аккаунт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
            managers=[
                ('description', django.db.models.manager.Manager()),
            ],
        ),
    ]
